import { config as defaultConfig } from "@/components/ui/gluestack-ui-provider/config";
import { createConfig } from "@gluestack-ui/themed";

export const themeConfig = createConfig({
  aliases: {
    bg: "backgroundColor",
    bgColor: "backgroundColor",
    m: "margin",
    mt: "marginTop",
    mr: "marginRight",
    mb: "marginBottom",
    ml: "marginLeft",
    mx: ["marginLeft", "marginRight"],
    my: ["marginTop", "marginBottom"],
    p: "padding",
    pt: "paddingTop",
    pr: "paddingRight",
    pb: "paddingBottom",
    pl: "paddingLeft",
    px: ["paddingLeft", "paddingRight"],
    py: ["paddingTop", "paddingBottom"],
    w: "width",
    h: "height",
    minW: "minWidth",
    minH: "minHeight",
    maxW: "maxWidth",
    maxH: "maxHeight",
  },
  tokens: {
    colors: {
      primary: "#3B82F6",
      success: "#22C55E",
      error: "#EF4444",
      info: "#EAB308",
      background: "#F9FAFB",
      textPrimary: "#111827",
      textSecondary: "#6B7280",
      white: "#FFFFFF",
      black: "#000000",
    },
    space: {
      0: 0,
      1: 4,
      2: 8,
      3: 12,
      4: 16,
      5: 20,
      6: 24,
      7: 28,
      8: 32,
      9: 36,
      10: 40,
      11: 44,
      12: 48,
    },
    fontSizes: {
      xs: 12,
      sm: 14,
      md: 16,
      lg: 18,
      xl: 20,
      "2xl": 24,
      "3xl": 30,
      "4xl": 36,
      "5xl": 48,
      "6xl": 60,
    },
  },
  light: {
    ...defaultConfig.light,
  },
  dark: {
    ...defaultConfig.dark,
  },
});
